# Generated by Django 4.0.5 on 2022-06-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('close_value', models.FloatField(blank=True, null=True, verbose_name='Закрытие котировки')),
                ('open_value', models.FloatField(blank=True, null=True, verbose_name='Открытие котировки')),
                ('high_value', models.FloatField(blank=True, null=True, verbose_name='Наивысшее значение')),
                ('low_value', models.FloatField(blank=True, null=True, verbose_name='Наименьшее значение')),
                ('money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.money')),
            ],
        ),
    ]
